{{- if not (empty .Values.Storage_Cred) }}
{{- $releaseNamespace := .Release.Namespace }}
  {{- range .Values.Storage_Cred }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .SecretName }}
  namespace: {{ $releaseNamespace }}
  labels:
    app: csi-driver
type: Opaque
data:
  {{- if not (empty .username) }}
  # set username to the base64 encoded user
  username: "{{ .username | b64enc }}"
  {{ else }}
  username: {{ required "Username is required!" .username }}
  {{- end }}
  {{- if not (empty .password) }}
  # set password to the base64 encoded password
  password: "{{ .password | b64enc }}"
  {{ else }}
  password: {{ required "Password is required!" .password }}
  {{- end }}
  {{- if not (empty .hostname) }}
  # set password to the base64 encoded password
  hostname: "{{ .hostname | b64enc }}"
  {{ else }}
  username: {{ required "hostname is required!" .hostname }}
  {{- end }}
  {{- end }}
{{- end }}
